- name: Instalar GPG key
  apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    state: present

- name: Agregar repo de Node
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ NODEJS_VERSION }}.x {{ ansible_distribution_release }} main"
    state: present
    update_cache: yes

- name: Instalar Node
  apt:
    name: nodejs
    state: present

- name: Instalar Angular CLI globalmente con NPM
  npm:
    name: '@angular/cli'
    global: yes
    state: present

- name: Crear un directorio para la app Angular
  file:
    path: my-angular-app
    state: directory
    owner: "ubuntu"
    group: "ubuntu"
    mode: '0755'

- name: Generar la app Angular con ng new
  command: ng new my-angular-app 

- name: Construir la app Angular
  command: ng build --prod --aot --env:prod
  args:
    chdir: my-angular-app


- name: Eliminar index por defecto
  ansible.builtin.file:
    path: /var/www/html/index.nginx-debian.html
    state: absent

- name: Copiar archivos a Nginx
  ansible.builtin.copy:
    src: /home/ubuntu/my-angular-app/dist/my-angular-app/browser
    dest: /var/www/html
    owner: root
    group: root
    mode: '0644'

